#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Create a new index.html file that will be used over the default index.nginx-debian.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html

# Redirect to /redirect_me to different link
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '38i\error_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
